SELECT TIM.DAY_KEY AS BATCH_DATE, s.*
FROM DBT_POC_DB.DBT_POC_TMP.TMP_SALES s
LEFT JOIN DBT_POC_DB.DBT_POC_TGT.TGT_LOCATION l ON s.LOCATION_ID = l.LOCATION_ID
LEFT JOIN  DBT_POC_DB.DBT_POC_TGT.TGT_PRODUCT p ON s.PRODUCT_ID = p.ITEM_ID
CROSS JOIN (SELECT MAX(DAY_KEY) as day_key FROM dbt_poc_db.dbt_poc_tgt.DWH_D_CURR_TIM_LU) TIM
WHERE l.LOCATION_ID IS NULL OR p.ITEM_ID IS NULL
